import {Item} from './ItemModel'
export const ItemData: Item[] = [
  {
    id: '1',
    title: '抽纸',
    image: $r('app.media.paper'),
    price: 15.5,
    specifications: [
      { title: '样式',
        data: [
          {title: '样式1', price: 0, image: $r('app.media.paper')},
          {title: '样式2', price: 10, image: $r('app.media.paper')},
          {title: '样式3', price: 20, image: $r('app.media.paper')}
        ]
      },
      { title: '品质',
        data: [
          {title: '品质1', price: 0, image: $r('app.media.paper')},
          {title: '品质2', price: 10, image: $r('app.media.paper')},
          {title: '品质3', price: 20, image: $r('app.media.paper')}
        ]
      }
    ],
    reviews:[
      '好好好',
      '不好'
    ]
  },
  {
    id: '2',
    title: '华为Mate60',
    image: $r('app.media.mate60'),
    price: 6999,
    specifications: [
      { title: '样式',
        data: [
          {title: '样式1', price: 15.5, image: ''},
          {title: '样式2', price: 25, image: ''},
          {title: '样式3', price: 35, image: ''}
        ]
      }
    ]
  },
  {
    id: '3',
    title: 'MateBookProX',
    image: $r('app.media.mateBookProX'),
    price: 13999,
    specifications: [
      { title: '样式',
        data: [
          {title: '样式1', price: 15.5, image: ''},
          {title: '样式2', price: 25, image: ''},
          {title: '样式3', price: 35, image: ''}
        ]
      }
    ]
  },
  {
    id: '4',
    title: 'WatchGT4',
    image: $r('app.media.watchGT4'),
    price: 1438,
    specifications: [
      { title: '样式',
        data: [
          {title: '样式1', price: 15.5, image: ''},
          {title: '样式2', price: 25, image: ''},
          {title: '样式3', price: 35, image: ''}
        ]
      }
    ]
  },
  {
    id: '5',
    title: 'FreeBuds Pro3',
    image: $r('app.media.freeBudsPro3'),
    price: 14999,
    specifications: [
      { title: '样式',
        data: [
          {title: '样式1', price: 15.5, image: ''},
          {title: '样式2', price: 25, image: ''},
          {title: '样式3', price: 35, image: ''}
        ]
      }
    ]
  },
  {
    id: '6',
    title: 'Mate X5',
    image: $r('app.media.mateX5'),
    price: 12999,
    specifications: [
      { title: '样式',
        data: [
          {title: '样式1', price: 15.5, image: ''},
          {title: '样式2', price: 25, image: ''},
          {title: '样式3', price: 35, image: ''}
        ]
      }
    ]
  },
  {
    id: '7',
    title: 'RX 580',
    image:('https://cdn.sapphiretech.com.cn/assets/consumer/11265_14_48_NITRO_RX_580_8G_G5_OC_C/11265_14_RX580_NITRO_plus_OC_8GB_800x500_01_C.png'),
    price: 200,
    specifications: [
      { title: '样式',
        data: [
          {title: '样式1', price: 15.5, image: ''},
          {title: '样式2', price: 25, image: ''},
          {title: '样式3', price: 35, image: ''}
        ]
      }
    ]
  },
  {
    id: '8',
    title: '1080Ti',
    image: ('https://www.nvidia.com/content/dam/en-zz/Solutions/GeForce/campaigns/10-series/geforce-1080-ti-2c50-D@2x.png'),
    price: 999,
    specifications: [
      { title: '样式',
        data: [
          {title: '样式1', price: 15.5, image: ''},
          {title: '样式2', price: 25, image: ''},
          {title: '样式3', price: 35, image: ''}
        ]
      }
    ]
  },
  {
    id: '9',
    title: 'ROG吹雪Z690-A',
    image: ('https://dlcdnwebimgs.asus.com.cn/gain/909D2123-4FEC-45C1-8F3B-C21E98EEAC3E/w717/h525'),
    price: 2499,
    specifications: [
      { title: '样式',
        data: [
          {title: '样式1', price: 15.5, image: ''},
          {title: '样式2', price: 25, image: ''},
          {title: '样式3', price: 35, image: ''}
        ]
      }
    ]
  },
  {
    id: '10',
    title: 'Arrona',
    image: ('https://cdnimg.gamekee.com/wiki2.0/images/w_252/h_204/829/43637/2022/6/2/909433.png'),
    price: 6999,
    specifications: [
      { title: '样式',
        data: [
          {title: '纯净版', price: 15.5, image: ''},
          {title: '加强版', price: 25, image: ''},
          {title: '黑化版', price: 35, image: ''}
        ]
      }
    ]
  },
  {
    id: '2',
    title: '华为Mate60',
    image: $r('app.media.mate60'),
    price: 6999,
    specifications: [
      { title: '样式',
        data: [
          {title: '样式1', price: 15.5, image: ''},
          {title: '样式2', price: 25, image: ''},
          {title: '样式3', price: 35, image: ''}
        ]
      }
    ]
  },
  {
    id: '2',
    title: '华为Mate60',
    image: $r('app.media.mate60'),
    price: 6999,
    specifications: [
      { title: '样式',
        data: [
          {title: '样式1', price: 15.5, image: ''},
          {title: '样式2', price: 25, image: ''},
          {title: '样式3', price: 35, image: ''}
        ]
      }
    ]
  },
  {
    id: '2',
    title: '华为Mate60',
    image: $r('app.media.mate60'),
    price: 6999,
    specifications: [
      { title: '样式',
        data: [
          {title: '样式1', price: 15.5, image: ''},
          {title: '样式2', price: 25, image: ''},
          {title: '样式3', price: 35, image: ''}
        ]
      }
    ]
  },
  {
    id: '2',
    title: '华为Mate60',
    image: $r('app.media.mate60'),
    price: 6999,
    specifications: [
      { title: '样式',
        data: [
          {title: '样式1', price: 15.5, image: ''},
          {title: '样式2', price: 25, image: ''},
          {title: '样式3', price: 35, image: ''}
        ]
      }
    ]
  },

]
